spring:
  datasource:
    url: jdbc:mariadb://198.13.47.188:19762/ApproveDB
    username: mrbluesky
    password: kang12!@
#    url: jdbc:mariadb://66.42.43.41:3306/projectdb
#    username: project
#    password: vmfhwprxm12#
  jpa:
    database: mysql
    #    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate # 운영시에는 validate 추천
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: false